# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  #pod 'VSSHCommunication', :path => './LocalLibs/VSSHCommunication'

  # Pods for Runner
  pod 'DynamicCodable', '1.0'

  post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8'
            end
        end
    end
end
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
